{% set name = "miniFasta" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/not-a-feature/miniFASTA/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 48a35ae0e6821b03dcc5e5151d3f51265d5d7062ae0c6e1fd1231a482c61064a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - miniFasta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/not-a-feature/miniFASTA
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A simple FASTA toolbox for small to medium size projects without dependencies.
  description: |
    A simple FASTA toolbox for small to medium size projects without dependencies.
  doc_url: https://github.com/not-a-feature/miniFASTA
  dev_url: https://github.com/not-a-feature/miniFASTA

extra:
  recipe-maintainers:
    - not-a-feature
