{% set name = "miniFasta" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/not-a-feature/miniFASTA/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e95cc342e63fe603934ed8bfab94e723ba9ce6a8e13e92c8bdb5075466098c11

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - miniFasta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/not-a-feature/miniFASTA
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A simple FASTA toolbox for small to medium size projects without dependencies.
  description: |
    A simple FASTA toolbox for small to medium size projects without dependencies.
  doc_url: https://github.com/not-a-feature/miniFASTA
  dev_url: https://github.com/not-a-feature/miniFASTA

extra:
  recipe-maintainers:
    - not-a-feature
